#!/usr/bin/env Rscript

# ----------------------------------------------------------------------------------------
# --- Process enzyme file
# ----------------------------------------------------------------------------------------

process_frag_file = function (enz_file, do.frag.count=TRUE, do.histogram=TRUE,
								target.min=NA, target.max=NA) {

	# Make a folder for output to go into
	out.dir = 'frag_analysis'
	if (!file.exists(out.dir)) {
		dir.create(out.dir)
	}
	
	# Read in fragment info generated by digest_simulation.pl
	frags = read.table(enz_file, sep="\t", header=FALSE, 
		col.names=c("Enzyme", "Contig", "Start", "End", "Length"),
		fill=TRUE)

	# Print number of frags (length of frags data.frame) to file
	if (do.frag.count) {
		write.table(paste(frags$Enzyme[1], dim(frags)[1], sep="\t"), 
			file="frag_analysis/enzyme_frag_counts_all.txt", 
			append=TRUE,
			quote=FALSE,
			row.names=FALSE,
			col.names=FALSE)
	}
	
	# Print number of frags with lengths in our target range to file
	right_sized_frags = frags[frags$Length >= target.min & frags$Length <= target.max,]
	write.table(paste(right_sized_frags$Enzyme[1], dim(right_sized_frags)[1], sep="\t"), 
		file="frag_analysis/enzyme_frag_counts_target.txt", 
		append=TRUE,
		quote=FALSE,
		row.names=FALSE,
		col.names=FALSE)
	
	# Make PDF histograms of length distribution
	if (do.histogram) {
		# All lengths:
		pdf(file=paste0("frag_analysis/lengths_", frags$Enzyme[1], ".pdf"),
			width=12)
			hist(frags$Length, 
				breaks=5000, 
				main=paste(frags$Enzyme[1], "Length Distribution"), 
				xlab=paste(frags$Enzyme[1], "Fragment Lengths (bp)"))
			abline(v=target.min, col='red')
			abline(v=target.max, col='red')
		dev.off()
		
		# Just those under 1000
		pdf(file=paste0("frag_analysis/lengths_under1000_", frags$Enzyme[1], ".pdf"),
			width=12)
			under_1000 = frags[frags$Length <= 1000,]
			hist(under_1000$Length, breaks=200, 
				main=paste(under_1000$Enzyme[1], "Length Distribution - Under 1000 bp"), 
				xlab=paste(under_1000$Enzyme[1], "Fragment Lengths (bp)"), col='grey')
			abline(v=target.min, col='red')
			abline(v=target.max, col='red')
		dev.off()
	}
	
	return(dim(frags))
}

usage = "Rscript process_frags.R enzyme_dir [target.min.bp] [target.max.bp]"
if (length(commandArgs(trailingOnly = TRUE)) < 1) {
	stop(usage)
}

# Get filename from command line
enz_dir = commandArgs(trailingOnly = TRUE)[1]

# Also get minimum and maximum of size distribution target
if (length(commandArgs(trailingOnly = TRUE)) == 3) {
	target.min = commandArgs(trailingOnly = TRUE)[2] # 120
	target.max = commandArgs(trailingOnly = TRUE)[3] # 200
}

# Get names of all enzyme files in input directory
files = dir(enz_dir, full.names=TRUE) 

# Process each file with the main function, process_frag_file
results = lapply(files, process_frag_file, 
					do.frag.count=TRUE, do.histogram=TRUE,
					target.min=target.min, target.max=target.max)
